Add support for racetime.gg race comparisons
LiveSplit/LiveSplit.Racetime pull request #8
Opened 2022-05-16 06:44 UTC by hwangbro

Requires https://github.com/racetimeGG/racetime-app/pull/172 to be merged before working.

Adds support for creating and updating real time race comparisons for racetime.gg. A lot of the implementation for this copies the SRL implementation.

2022-05-16 16:01 UTC, deains reviewed
👀

2022-05-16 16:01 UTC, deains commented on Controller/RacetimeChannel.cs
> +                string cmd = "{ \"action\": \"split\", \"data\": { \"split\":\"" + split.Name + "\", \"time\": \"-\"} }";
Presumably C# has a JSON encode function somewhere? `split.Name` could contain `"` or other characters that could mess up encoding. I see as well we're using this for chat messages which is rather janky so might be good to fix that too!

2022-05-16 17:22 UTC, wooferzfg commented on Controller/RacetimeChannel.cs
> +                string cmd = "{ \"action\": \"split\", \"data\": { \"split\":\"" + split.Name + "\", \"time\": \"-\"} }";
LiveSplit has a `DynamicJsonObject` class: https://github.com/LiveSplit/LiveSplit/blob/b893917f51245bfc5dfbc890114a32de76cfa0c8/LiveSplit/LiveSplit.Core/Web/JSON.cs#L147

2022-05-17 03:20 UTC, Killklli requested changes

2022-05-17 03:20 UTC, Killklli commented on Controller/RacetimeChannel.cs
> +            UpdateRaceComparisons(Race);
As msg.Race can be null in cases and we're only setting race in those chases, we should probably move this within the if statement

2022-06-21 07:52 UTC, merged